import Head from 'next/head'

export default function Home({posts}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
					{ posts.map((post) => (
						<div>{post.title}</div>
					)) }
      </main>
    </>
  )
}

export const getServerSideProps = async() => {
	const res = await fetch('https://jsonplaceholder.typicode.com/posts?_start=0&_end=10')
	const posts = await res.json();
	
	return {
		props: {
			posts
		}
	}
}